DummyProject/DummyProject/AppDelegate.swift
DummyProject/DummyProject/Base.lproj/Main.storyboard
DummyProject/DummyProject/ViewController.swift

There's a screenshot on the document for the demo app. https://livestyled.atlassian.net/wiki/spaces/Tech/pages/2439970817/iOS+SDKs#What-to-Test?

Improve demo app for friendly testing

---

Core/APIUtilities/APIRequester.swift
Core/APIUtilities/APITokenManager/APITokenManagable.swift
Core/APIUtilities/APITokenManager/APITokenManager.swift
Core/APIUtilities/APITokenManager/OAuthTokenHelpers/OAuthRefreshOrWaitActionGenerator.swift
Core/APIUtilities/Tests/APIRequesterTests.swift
Core/APIUtilities/Tests/APITokenManagerTests.swift
Core/APIUtilities/Tests/EmptyTokenManagerTests.swift
Core/APIUtilities/Tests/OAuthRefreshOrWaitActionGeneratorTests.swift
Core/CoreFactory.swift
Core/GraphQL/APITokenInterceptor.swift
RealifeTech-SDK.xcodeproj/project.pbxproj
RealifeTech/SDKFactory.swift

Update the Core interface with the refreshing token hotfixes of CoreSDK

ID-604 Update Core interface with the token hotfixes of CoreSDK

---

Core/GraphQL/API/sell_checkoutMyBasket.graphql.swift
Core/GraphQL/API/sell_createMyBasket.graphql.swift
Core/GraphQL/API/sell_createPaymentIntent.graphql.swift
Core/GraphQL/API/sell_fragment_product.graphql.swift
Core/GraphQL/API/sell_fragment_products.graphql.swift
Core/GraphQL/API/sell_getMyPaymentSources.graphql.swift
Core/GraphQL/API/sell_getOrders.graphql.swift
Core/GraphQL/API/sell_getProductById.graphql.swift
Core/GraphQL/API/sell_getProducts.graphql.swift
Core/GraphQL/API/sell_updateMyBasket.graphql.swift
Core/GraphQL/API/sell_updatePaymentIntent.graphql.swift
Core/GraphQL/GraphQLFiles/sell_createPaymentIntent.graphql
Core/GraphQL/GraphQLFiles/sell_getMyPaymentSources.graphql
Core/GraphQL/GraphQLFiles/sell_updatePaymentIntent.graphql
Core/GraphQL/schema.json
RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj

1. Add `nextPage`, `lastPage` and `firstPage` for **getMyPaymentSources**
2. Add `lastPaymentError` for **createPaymentIntent** and **updatePaymentIntent**
3. Bump version to 1.2.3
Note: There are some changed files related to basket and product under GraphQL/API, which were auto generated by Apollo after I run the build.

Update query string for VGS

---

Core/GraphQL/API/Types.graphql.swift
Core/GraphQL/API/sell_fragment_fulfilmentPoint.graphql.swift
Core/GraphQL/API/sell_fragment_fulfilmentPointCategory.graphql.swift
Core/GraphQL/API/sell_fragment_order.graphql.swift
Core/GraphQL/API/sell_fragment_timeslot.graphql.swift
Core/GraphQL/API/sell_getFulfilmentPointCategories.graphql.swift
Core/GraphQL/API/sell_getFulfilmentPointCategoryById.graphql.swift
Core/GraphQL/API/sell_getOrders.graphql.swift
Core/GraphQL/API/sell_updatePaymentIntent.graphql.swift
Core/GraphQL/GraphQLFiles/sell_fragment_fulfilmentPoint.graphql
Core/GraphQL/GraphQLFiles/sell_fragment_fulfilmentPointCategory.graphql
Core/GraphQL/GraphQLFiles/sell_fragment_order.graphql
Core/GraphQL/GraphQLFiles/sell_fragment_orders.graphql
Core/GraphQL/GraphQLFiles/sell_fragment_timeslot.graphql
Core/GraphQL/GraphQLFiles/sell_getFulfilmentPointCategories.graphql
Core/GraphQL/GraphQLFiles/sell_getFulfilmentPointCategoryById.graphql
Core/GraphQL/GraphQLFiles/sell_getFulfilmentPoints.graphql
Core/GraphQL/GraphQLFiles/sell_getOrders.graphql
Core/GraphQL/GraphQLFiles/sell_updatePaymentIntent.graphql
Core/GraphQL/schema.json
RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj

1. Download new GraphQL schema
2. Change `updateMyPaymentIntent` input type from `PaymentIntentInput` to `PaymentIntentUpdateInput`
3. In order to pass compiling with new schema, I also update graphql files for `FulfilmentPointCategory` and `Order`
4. Bump version to 1.2.4

Update GraphQL schema

---

Core/GraphQL/API/sell_fragment_basket.graphql.swift
Core/GraphQL/API/sell_getMyBasket.graphql.swift
Core/GraphQL/GraphQLFiles/sell_fragment_basket.graphql
Core/GraphQL/GraphQLFiles/sell_getMyBasket.graphql
RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Basket/Models/Basket.swift
Sell/Basket/Models/BasketItem.swift
Sell/Basket/Models/CollectionPreferenceType.swift
Sell/Basket/Models/SeatInfo.swift

Updating fragments, query and mutations in this PR.

ID-1026 Basket (part 1)

---

Core/APILayer/Util/APIError.swift
Core/APIUtilities/StandardSenderResponse.swift
RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj

Make `title`, `message`, `statusCode` and other neccessary fields public for app uses.

Public some properties of APIError

---

Core/GraphQL/API/sell_deleteMyPaymentSource.graphql.swift
Core/GraphQL/GraphQLFiles/sell_deleteMyPaymentSource.graphql
RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj

1. Add VGS `deleteMyPaymentSource` mutation
2. Bump version to 1.2.6

ID-889 VGS deleteMyPaymentSource mutation

---

Core/GraphQL/API/Types.graphql.swift
Core/GraphQL/API/sell_getFulfilmentPointById.graphql.swift
Core/GraphQL/API/sell_getFulfilmentPoints.graphql.swift
Core/GraphQL/API/sell_getProductById.graphql.swift
Core/GraphQL/API/sell_getProducts.graphql.swift
Core/GraphQL/GraphQLFiles/sell_getFulfilmentPointById.graphql
Core/GraphQL/GraphQLFiles/sell_getFulfilmentPoints.graphql
Core/GraphQL/GraphQLFiles/sell_getProductById.graphql
Core/GraphQL/GraphQLFiles/sell_getProducts.graphql
Core/GraphQL/Tests/GraphQLManagerTests.swift
Core/GraphQL/schema.json
RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/FulfilmentPoint/Models/FulfilmentPointFilter.swift
Sell/FulfilmentPoint/Repository/FulfilmentPointProvidable.swift
Sell/FulfilmentPoint/Repository/FulfilmentPointRepository.swift
Sell/FulfilmentPoint/Tests/FulfilmentPointRepositoryTests.swift
Sell/Product/Repository/ProductProvidable.swift
Sell/Product/Repository/ProductRepository.swift
Sell/Product/Tests/ProductRepositoryTests.swift
Sell/Utils/FilterParam.swift

BE has added `FilterParam` object to these queries and this PR applies the changes to the queries.
```
getFulfilmentPoints
getFulfilmentPoint
getProducts
getProduct
```

Sell: Add FilterParam input to queries

---

RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Product/Tests/ProductCategoryTests.swift
Sell/Product/Tests/ProductFilterTests.swift
Sell/Product/Tests/ProductModifierItemSelectionInputTests.swift
Sell/Product/Tests/ProductModifierItemTests.swift
Sell/Product/Tests/ProductModifierListTests.swift
Sell/Product/Tests/ProductTests.swift

WOD-22 Unit Test Sell - Product models

---

RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Payment/Models/PaymentIntent/PaymentIntent.swift
Sell/Payment/Models/PaymentIntent/PaymentIntentNextAction.swift
Sell/Payment/Tests/CancellationReasonTests.swift
Sell/Payment/Tests/CardInputTests.swift
Sell/Payment/Tests/CardTests.swift
Sell/Payment/Tests/OrderTypeTests.swift
Sell/Payment/Tests/PaymentActionTypeTests.swift
Sell/Payment/Tests/PaymentIntentNextActionTests.swift
Sell/Payment/Tests/PaymentIntentTests.swift
Sell/Payment/Tests/PaymentSourceTests.swift
Sell/Payment/Tests/PaymentStatusTests.swift
Sell/Product/Tests/ProductCategoryTests.swift
Sell/Product/Tests/ProductFilterTests.swift
Sell/Product/Tests/ProductModifierItemSelectionInputTests.swift
Sell/Product/Tests/ProductModifierItemTests.swift
Sell/Product/Tests/ProductModifierListTests.swift
Sell/Product/Tests/ProductTests.swift

Unit test payment source and payment intent models. Sheet is also updated.

WOD-22 Unit Test Sell - Payment models

---

RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Basket/Repository/BasketError.swift
Sell/Basket/Tests/BasketErrorTests.swift
Sell/Order/Tests/OrderItemTests.swift
Sell/Order/Tests/OrderModelTestsHelper.swift
Sell/Order/Tests/OrderTests.swift
Sell/Payment/Models/PaymentIntent/PaymentIntent.swift
Sell/Payment/Models/PaymentIntent/PaymentIntentNextAction.swift
Sell/Payment/Tests/CancellationReasonTests.swift
Sell/Payment/Tests/CardInputTests.swift
Sell/Payment/Tests/CardTests.swift
Sell/Payment/Tests/OrderTypeTests.swift
Sell/Payment/Tests/PaymentActionTypeTests.swift
Sell/Payment/Tests/PaymentIntentNextActionTests.swift
Sell/Payment/Tests/PaymentIntentTests.swift
Sell/Payment/Tests/PaymentSourceTests.swift
Sell/Payment/Tests/PaymentStatusTests.swift
Sell/Product/Tests/ProductCategoryTests.swift
Sell/Product/Tests/ProductFilterTests.swift
Sell/Product/Tests/ProductModifierItemSelectionInputTests.swift
Sell/Product/Tests/ProductModifierItemTests.swift
Sell/Product/Tests/ProductModifierListTests.swift
Sell/Product/Tests/ProductTests.swift

CodeCoverageIncrease sheet updated.

WOD-22 Unit Test Sell - Order models

---

Core/GraphQL/Utils/String+ISO8601Date.swift
GraphQL/API/Types.graphql.swift
GraphQL/API/sell_checkoutMyBasket.graphql.swift
GraphQL/API/sell_createMyBasket.graphql.swift
GraphQL/API/sell_createPaymentIntent.graphql.swift
GraphQL/API/sell_deleteMyBasket.graphql.swift
GraphQL/API/sell_fragment_basket.graphql.swift
GraphQL/API/sell_fragment_order.graphql.swift
GraphQL/API/sell_fragment_paymentSource.graphql.swift
GraphQL/API/sell_getMyBasket.graphql.swift
GraphQL/API/sell_getMyOrder.graphql.swift
GraphQL/API/sell_getOrders.graphql.swift
GraphQL/API/sell_updateMyBasket.graphql.swift
GraphQL/API/sell_updateMyOrder.graphql.swift
GraphQL/GraphQLFiles/sell_fragment_basket.graphql
GraphQL/GraphQLFiles/sell_fragment_order.graphql
GraphQL/GraphQLFiles/sell_fragment_seatInfo.graphql
GraphQL/JSON+Helper.swift
GraphQL/schema.json
RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Basket/Models/Basket.swift
Sell/Basket/Models/SeatInfo.swift
Sell/Basket/Repository/BasketRepository.swift
Sell/Order/Models/Order.swift
Sell/Payment/Models/PaymentSource/PaymentSourceBillingDetails.swift

Backend has changed SeatInfo type from `SeatInfo` to `JSON` on GraphQL schema
The solution in this PR comes from here: https://github.com/apollographql/apollo-ios/issues/36#issuecomment-452515484
1. Add `--passthroughCustomScalars` to the build phase
2. Add the `typealias` for JSON

Update SeatInfo Type 

---

RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj
Sell/Basket/Models/Basket.swift
Sell/Basket/Models/SeatInfo.swift
Sell/Basket/Tests/SeatInfoTests.swift
Sell/Order/Models/Order.swift

Found this bug when adding unit tests.

Added missing exclamation mark on SeatInfo initialiser

---

Identity/Identity.swift
Identity/IdentityFactory.swift
Identity/IdentityImplementing.swift
Identity/Tests/IdentityImplementingTests.swift
RealifeTech-SDK.xcodeproj/project.pbxproj
RealifeTech/RealifeTech.swift
RealifeTech/Tests/RealifeTechTests.swift

Implement identity module and use for isHostAppLoginDeepLink

---

.swiftlint.yml
Analytics/AnalyticsFactory.swift
Analytics/AnalyticsLogging/AnalyticsLogger.swift
Analytics/Tests/AnalyticsFactoryTests.swift
Analytics/Tests/AnalyticsLoggingTests/AnalyticsLoggerTests.swift
CampaignAutomation/Tests/CampaignAutomationImplementingTests.swift
Core/Logging/AnalyticEvent.swift
Identity/Identity.swift
Identity/IdentityFactory.swift
Identity/IdentityImplementing.swift
Identity/Persistence/IdentityPersister.swift
Identity/Persistence/IdentityPersisting.swift
Identity/Tests/IdentityImplementingTests.swift
RealifeTech-SDK.xcodeproj/project.pbxproj
RealifeTech/RealifeTech.swift
RealifeTech/Tests/RealifeTechTests.swift
SampleApp/Podfile.lock
SampleApp/SampleApp.xcodeproj/project.pbxproj
SampleApp/SampleApp/Screens/IdentityView.swift
SampleApp/SampleApp/Screens/ModulesView.swift

I’ve taken this as far as I can. I need backend to add the new userId field to the PutAnalyticEvent mutation so I can pull in the new schema, test, and close this off.
@aleksandrspr can you give it a first round of code review to get ahead of any delays?

[WIP] Feature/catd 124

---

GraphQL/API/GeneralGQLAPI.swift
GraphQL/GraphQLFiles/General/sell_getMyUserSSO.graphql
GraphQL/schema.json
Identity/Identity.swift
Identity/IdentityFactory.swift
Identity/IdentityImplementing.swift
Identity/SSO/SSOProvidable.swift
Identity/SSO/SSORepository.swift
Identity/SSO/Tests/SSORepositoryTests.swift
Identity/Tests/IdentityImplementingTests.swift
RealifeTech-SDK.xcodeproj/project.pbxproj
RealifeTech/RealifeTech.swift

Implemented new query
```
query: getMyUserSSO: UserSSO
type UserSSO: {
id: ID
sub: String
}
```

MOD-797 Implement getMyUserSSO query

---

SampleApp/Podfile.lock
SampleApp/SampleApp.xcodeproj/project.pbxproj
SampleApp/SampleApp/Screens/Components/BannerView.swift
SampleApp/SampleApp/Screens/CreatablesView.swift
SampleApp/SampleApp/Screens/ModulesView.swift
SampleApp/SampleApp/Screens/Util/ImageLoader.swift

CATD-429 Display banner image in Sample App

---

SampleApp/SampleApp/Screens/Components/TextInput.swift
SampleApp/SampleApp/Screens/EventsLoggingView.swift
SampleApp/SampleApp/Screens/IdentityView.swift
SampleApp/SampleApp/Screens/ModulesView.swift

Fixed: Changes to the bottom field on this view are not reflected in logged analytic events, where they should be.

CATD-401-a Sample App log analytic event changed body not sent

---

SampleApp/SampleApp.xcodeproj/project.pbxproj
SampleApp/SampleApp/Delegates/AppDelegate.swift
SampleApp/SampleApp/Screens/AudienceCheckingView.swift
SampleApp/SampleApp/Screens/CreatablesView.swift
SampleApp/SampleApp/Screens/DeviceRegistrationView.swift
SampleApp/SampleApp/Screens/EventsLoggingView.swift
SampleApp/SampleApp/Screens/IdentityView.swift
SampleApp/SampleApp/Screens/ModulesView.swift
SampleApp/SampleApp/Screens/Util/ErrorHandler.swift
SampleApp/SampleApp/Screens/Util/NotificationRegistrationHelper.swift
SampleApp/SampleApp/Screens/Util/StandardError.swift
SampleApp/SampleApp/Screens/WebOrderingJourneyView.swift
SampleApp/SampleApp/Screens/WebPageTypeGetterView.swift

- Show alert when device hasn't been registered.

CATD-533 Add TextFields for inputting appCode and clientSecret on Device Registration page

---

SampleApp/Podfile.lock
SampleApp/SampleApp/Screens/CreatablesView.swift

Added TextField for user to input any campaign ID

CATD-574 Remove hardcoded campaign ID

---

CampaignAutomation/CampaignAutomation.swift
CampaignAutomation/CampaignAutomationImplementing.swift
CampaignAutomation/Models/RLTBanner.swift
CampaignAutomation/Models/RLTContentItem.swift
CampaignAutomation/Models/RLTItem.swift
CampaignAutomation/Models/RLTLinkHandling.swift
CampaignAutomation/Tests/CampaignAutomationImplementingTests.swift
CampaignAutomation/Tests/RLTLinkHandlingTests.swift
RealifeTech-SDK.xcodeproj/project.pbxproj
SampleApp/Podfile.lock
SampleApp/SampleApp/Screens/CreatablesView.swift

- Implement ability to fetch CA data
- Fixed: when url is an invalid URL, the view is not generated.

CATD-711 Implement ability to fetch CA data

---

Communicate/CommunicateImplementing.swift
Communicate/Tests/CommunicateImplementingTests.swift

Should extract track from trackInfo payload

Fixed trackPush mutation

---

RealifeTech-SDK.podspec
RealifeTech-SDK.xcodeproj/project.pbxproj

Fix SwiftLint version in podspec file.

Develop > master 1.15.1
